### ISSUE TITLE
Too many separate workflows flood notification of contributors

### ISSUE THREAD

**Issue by LouisCAD** [typesafegithub/github-workflows-kt#1114]
Hello

Here just a small part of all the workflow notifications I got from my contribution in #1109 

Further ping-pong made it grow like crazy, well in the hundreds most likely, I didn't count, let alone reviewing any of those.

<img width="1214" alt="Screenshot 2023-11-18 at 18 37 31" src="https://github.com/typesafegithub/github-workflows-kt/assets/6975237/4f9adf40-eb6a-42da-af18-e8b1626dce06">

This drowns helpful notifications out. I think it'd be great to group all of the checks into a single workflow with multiple jobs. Now that you're using Kotlin, it would probably be easier to do.

**Comment by krzema12** [comment]
Wow, I don't get these! Especially the success notifications surprise me. Do you have some verbose mode turned on? Or maybe I have certain types of notifications turned off.
@Vampire do you also get these?

**Comment by LouisCAD** [comment]
It's just the default for my fork. GitHub should probably group/conflate those too, but in the meantime, you know why this project even exists, right… so maybe rolling our own solution, if it affects other contributors too (which I believe is the case, TBD), is our shortest path.

**Comment by krzema12** [comment]
Ok, for sure we could put all integration steps in a single workflow, it should make things less noisy. It will be a bit challenging on the implementation side, but doable.

**Comment by Vampire** [comment]
I don't remember having them.
But I also don't look at GitHub notifications too often, but mainly just look for the E-Mails GitHub is sending.
Currently I only can filter for these, but this does not include any PR by me:
![image](https://github.com/typesafegithub/github-workflows-kt/assets/325196/50152fdd-f199-4f52-a920-9a2b7f45a6ec)

**Comment by Vampire** [comment]
But I also only have this for setup-wsl and there jobs are running at least daily and I'm pretty sure I did not change settings for that:
![image](https://github.com/typesafegithub/github-workflows-kt/assets/325196/59a0b2d3-a902-4e04-91e4-09314cdb88c6)

**Comment by Vampire** [comment]
Probably this configuration option:
![image](https://github.com/typesafegithub/github-workflows-kt/assets/325196/a082b745-0f7b-4a87-81b8-9b31a1838f09)

**Comment by krzema12** [comment]
Yeah, I have the above configuration. Still I'll consolidate all integration tests into a single workflow, it will make it easier to read the status in the PRs, too.

**Comment by krzema12** [comment]
Ok, some changes that should improve it have landed. Resolving - let's revisit if it's still painful.
