### ISSUE TITLE
[Bug] step-1 ("Execute script") of "Check YAML consistency" job is broken if generated from project root

### ISSUE THREAD

**Issue by LouisCAD** [typesafegithub/github-workflows-kt#1192]
# Action

I ran my workflow generating script from the root folder using the following shell command:

`./.github/workflows/publish-plugins.main.kts`

# Expected

The same content is generated as if I run as `./publish-plugins.main.kts` from the `.github/workflows` directory.

# Actual

`run: 'rm ''.github/workflows/publish-plugins.yaml'' && ''publish-plugins.main.kts'''`

was generated instead of

`run: 'rm ''.github/workflows/publish-plugins.yaml'' && ''.github/workflows/publish-plugins.main.kts'''`.

It failed on GitHub at the "Check YAML consistency" job, step "Execute script" because the path to the script was wrong.

https://github.com/Splitties/gradle-dependencies-dsl/actions/runs/7227552380/job/19695431873

# Workaround

I ran the script it again after running `cd .github/workflows`, and committed the changes: https://github.com/Splitties/gradle-dependencies-dsl/commit/c273d68a1c7b10325ed38dae182d5f283e5ce9e4

# Library version

v1.7.0

**Comment by krzema12** [comment]
Was it working fine for you in the past?

Generally it should already work the same way in both cases. See e. g. the workflows in this repo:
https://github.com/typesafegithub/github-workflows-kt/blob/77d8c4ebd6c8bbc533a381e9d14c2b9a8992aa34/.github/workflows/build.yaml#L24
If the bug was reproducible in this case, the consistency check would produce a different YAML here.

@Vampire do you have a minute to take a look? I'm having a busy time.

**Comment by LouisCAD** [comment]
I think it's the first time I'm running it manually from a terminal where the working directory is the project root.

All the other times, I was running it with the run button in IntelliJ (it is lacking in Fleet 😅), and that leads to it being run from the script directory in a terminal tab, where there's no bug.

**Comment by krzema12** [comment]
@LouisCAD could you first check if you aren't affected by this issue with the Kotlin script cache? https://youtrack.jetbrains.com/issue/KT-64367/

**Comment by krzema12** [comment]
I got a similar result to yours with such reproduction:

```
piotr@Piotrs-MacBook-Air gradle-dependencies-dsl % .github/workflows/publish-plugins.main.kts 
piotr@Piotrs-MacBook-Air gradle-dependencies-dsl % git st
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
piotr@Piotrs-MacBook-Air gradle-dependencies-dsl % cd .github/workflows 
piotr@Piotrs-MacBook-Air workflows % ./publish-plugins.main.kts 
piotr@Piotrs-MacBook-Air workflows % git st
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   publish-plugins.yaml

no changes added to commit (use "git add" and/or "git commit -a")
piotr@Piotrs-MacBook-Air workflows % git diff
diff --git a/.github/workflows/publish-plugins.yaml b/.github/workflows/publish-plugins.yaml
index a2b4630..9e2877b 100644
--- a/.github/workflows/publish-plugins.yaml
+++ b/.github/workflows/publish-plugins.yaml
@@ -1,4 +1,4 @@
-# This file was generated using Kotlin DSL (.github/workflows/publish-plugins.main.kts).
+# This file was generated using Kotlin DSL (.github/workflows/.github/workflows/publish-plugins.main.kts).
 # If you want to modify the workflow, please change the Kotlin file and regenerate this YAML file.
 # Generated with https://github.com/typesafegithub/github-workflows-kt
 
@@ -22,7 +22,7 @@ jobs:
       uses: 'actions/checkout@v4'
     - id: 'step-1'
       name: 'Execute script'
-      run: 'rm ''.github/workflows/publish-plugins.yaml'' && ''.github/workflows/publish-plugins.main.kts'''
+      run: 'rm ''.github/workflows/publish-plugins.yaml'' && ''.github/workflows/.github/workflows/publish-plugins.main.kts'''
     - id: 'step-2'
       name: 'Consistency check'
       run: 'git diff --exit-code ''.github/workflows/publish-plugins.yaml'''
piotr@Piotrs-MacBook-Air workflows % rm -rf ~/Library/Caches/main.kts.compiled.cache/
piotr@Piotrs-MacBook-Air workflows % ./publish-plugins.main.kts                      
piotr@Piotrs-MacBook-Air workflows % git st
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
piotr@Piotrs-MacBook-Air workflows % 
```

@LouisCAD please confirm if cleaning the cache makes the script work correctly.

**Comment by krzema12** [comment]
Resolving as not really a bug with the library. Please reopen if needed.
