### ISSUE TITLE
Investigate deeper Petals cache persistance on action-bindings

### ISSUE THREAD

**Issue by LeoColman** [typesafegithub/github-workflows-kt#1206]
https://kotlinlang.slack.com/archives/C02UUATR7RC/p1703337896816589

**Comment by krzema12** [comment]
@LeoColman next idea: please introduce a dummy change in your script (even an empty line) and then rerun it. The idea is to force-recompile the script in case the technique of cleaning the cache is incorrect.

**Comment by LeoColman** [comment]
Adding an empty line generated the right file.
I had tried that before tho, so I think something else must have happened to invalidate the cache.
This is no longer reproduceable in my machine :(

**Comment by krzema12** [comment]
Ok, let me resolve this issue for now since it doesn't seem to be related to the library and we don't have a reproducer.
