### ISSUE TITLE
Add a utility to list available versions for actions

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#1398]
Some people don't like dependency updating bots like Renovate or Dependabot, and use on-demand available versions listing with e.g. https://github.com/Splitties/refreshVersions. Since refreshVersions doesn't support Kotlin scripting, there's an idea add support for listing available versions as a separate library, hosted in github-workflows-kt monorepo.

**Comment by krzema12** [comment]
In progress in #1393 by @NikkyAI.

**Comment by krzema12** [comment]
@NikkyAI I think it would be nice to add some minimal docs.

**Comment by NikkyAI** [comment]
we have kdoc on the function ( might need to configure dokka in the module)
I guess you want docs for the website too though ?

**Comment by krzema12** [comment]
Let's ass the docs once needed.
