### ISSUE TITLE
[Core feature request] Do not return `Workflow` instance from `workflow { ... }`

### ISSUE THREAD

**Issue by Vampire** [typesafegithub/github-workflows-kt#1464]
With the API changes in 2.0.0 you typically call `workflow { ... }` as last action in the script.
Before you called `writeToFile()` on the returned `Workflow` instance.
As now the `workflow { ... }` call is the last statement its return value is the Script result and its `toString()`  is printed to the console.
This is a bit of a visual clutter.

The `workflow { ... }` call should return `Unit` instead and have a parameter that receives a callback to process the `Workflow` instance for cases where this is needed.

Work-arounds besides ignoring the output would be to just have another statement after the call that returns `Unit` (for example just a line with `Unit` on its own), or to assign the result to a variable.

**Comment by krzema12** [comment]
Left to do: remove returning `Workflow` from the `workflow` function. It should happen in 3.0 because it's a breaking change.
