### ISSUE TITLE
[Bug] `RepositoryDispatch` misses `types` parameter

### ISSUE THREAD

**Issue by Vampire** [typesafegithub/github-workflows-kt#1573]
# Action

https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch supports custom activity types to differentiate webhook calls.

# Expected

A `types` parameter with type `List<String>` to configure the types.

# Actual

No parameter present

# Library version

v2.3.0

**Comment by krzema12** [comment]
Thanks!
To be added to https://github.com/typesafegithub/github-workflows-kt/blob/d06b800de71dcba314451fd799a0c02b3a7d9b27/github-workflows-kt/src/main/kotlin/io/github/typesafegithub/workflows/domain/triggers/RepositoryDispatch.kt#L10 and passed down the serialization path.

**Comment by Vampire** [comment]
Wow, that was fast, thanks. :-D
