### ISSUE TITLE
[Core feature request] CommandStep is missing way to access outputs

### ISSUE THREAD

**Issue by Vampire** [typesafegithub/github-workflows-kt#1587]
You can set outputs in command steps, for example like `echo 'found=true' >>"$GITHUB_OUTPUT"`.
But the `CommandStep` is missing the `outputs` property, so to access it you have to do `steps.${myPreviousStep.id}.outputs.found` instead of the usual `${myPreviousStep.outputs["found"]`.

**Comment by krzema12** [comment]
Yes! Would you like to contribute this one?
