### ISSUE TITLE
[Bug] Using nested actions from Gradle doesn't work

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#1694]
# Component

* [ ] github-workflows-kt (library with the DSL)
* [X] bindings server (https://bindings.krzeminski.it)
* [ ] I don't know

# Action

Use an action that is not in some repo's root directory, from a Gradle project:

```kotlin
implementation("gradle:actions__setup-gradle:v4")
```

# Expected

Works like with Kotlin Scripting.

# Actual

```
Configuration cache state could not be cached: field `provider` of `org.gradle.internal.serialize.codecs.core.ProviderBackedFileCollectionSpec` bean found in field `element` of `java.util.Collections$SingletonList` bean found in field `elements` of `org.gradle.internal.serialize.codecs.core.ResolutionBackedFileCollectionSpec` bean found in field `__classpathSnapshot__` of `org.jetbrains.kotlin.gradle.tasks.KotlinCompile$ClasspathSnapshotProperties` bean found in field `__classpathSnapshotProperties__` of task `:github-workflows-kt:compileTestKotlin` of type `org.jetbrains.kotlin.gradle.tasks.KotlinCompile`: error writing value of type 'org.gradle.api.internal.provider.DefaultProvider'
For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
> Could not resolve all files for configuration ':github-workflows-kt:testCompileClasspath'.
10 actionable tasks: 4 executed, 6 from cache
   > Could not resolve gradle:actions__setup-gradle:v4.
     Required by:
         project :github-workflows-kt
      > Could not resolve gradle:actions__setup-gradle:v4.
         > inconsistent module metadata found. Descriptor: gradle:actions/setup-gradle:v4 Errors: bad module name: expected='actions__setup-gradle' found='actions/setup-gradle'
```

Reproducer: https://github.com/typesafegithub/github-workflows-kt/pull/1693 

# Workaround, if exists

```kotlin
repositories {
    maven {
        ...
        metadataSources {
            artifact()
        }
    }
}
```

**Comment by krzema12** [comment]
Noticed by @mareklangiewicz.

**Comment by krzema12** [comment]
I suspect we'd need to adjust https://github.com/typesafegithub/github-workflows-kt/blob/a5b842ce42639b214df137a25ec45b9c9aa1a9f5/maven-binding-builder/src/main/kotlin/io/github/typesafegithub/workflows/mavenbinding/MavenMetadataBuilding.kt#L23 but not sure what consequences it would have for parts that now work.

**Comment by Vampire** [comment]
That's known and will be fixed by #1608.
As a temporary work-around you could disable usage of Gradle Module Metadata for the repository until the fix is live.

**Comment by Vampire** [comment]
That's known and will be fixed by #1608.
As a temporary work-around you could disable usage of Gradle Module Metadata for the repository until the fix is live.

**Comment by Vampire** [comment]
```kotlin
repositories {
    maven {
        ...
        metadataSources {
            ignoreGradleMetadataRedirection()
        }
    }
}
```

**Comment by mareklangiewicz** [comment]
> ```kotlin
> repositories {
>     maven {
>         ...
>         metadataSources {
>             ignoreGradleMetadataRedirection()
>         }
>     }
> }
> ```
@Vampire 
This doesn't help. Still the same error:
```
      > Could not resolve gradle:actions__setup-gradle:v4.
         > inconsistent module metadata found. Descriptor: gradle:actions/setup-gradle:v4 Errors: bad module name: expected='actions__setup-gradle' found='actions/setup-gradle'
 ```
Maybe it's some kind of gradle safety feature checking the .pom <artifactId> or <description> or sth?
https://bindings.krzeminski.it/gradle/actions__setup-gradle/v4/actions__setup-gradle-v4.pom

**Comment by Vampire** [comment]
Ah, it is the pom, was tricked by "metadata". Then it is #1609 that will fix it. And the work-around is to disable pom usage for now using 
```kotlin
repositories {
    maven {
        ...
        metadataSources {
            artifact()
        }
    }
}
```

**Comment by mareklangiewicz** [comment]
> Ah, it is the pom, was tricked by "metadata". Then it is #1609 that will fix it. And the work-around is to disable pom usage for now using
> 
> ```kotlin
> repositories {
>     maven {
>         ...
>         metadataSources {
>             artifact()
>         }
>     }
> }
> ```

That doesn't work either. From the stacktrace I can see that gradle probably keeps failing on this line:
https://github.com/gradle/gradle/blob/3a1f8427b9455b1d1620048a9a2c1f0a4f2b727b/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/repositories/metadata/AbstractRepositoryMetadataSource.java#L123

**Comment by Vampire** [comment]
Stop using `mavenLocal()`, it is broken-by-design in Maven already.
If you really really really need to use it, at least have it as last in the list of repositories and always with a repository content filter that defines what exactly should come from there.

**Comment by krzema12** [comment]
@Vampire sorry, I missed any mention of Maven Local. How is it related to this ticket?

Regarding the bug, I've just merged a nice refactoring from @Vampire that will help avoiding such bugs in the future. Next steps:
* add a reproducing test by adding a small Gradle module/project that consumes a top-level action and an action under some path. Call it from the GitHub workflow that starts the server locally
* rebase and merge #1609 plus other PRs related to fixing names in various metadata files

**Comment by Vampire** [comment]
> sorry, I missed any mention of Maven Local. How is it related to this ticket?

It was implicit and coming from my gut feeling. :-D

My work-around does work, I tried it. 
As it did not work it must come from a different repository. 
One possibility is that the work-around was done on the wrong repository.
Another - much more likely - possibility is, that Maven Local is used as repository and that the broken POM is still read from there. :-)

**Comment by krzema12** [comment]
@mareklangiewicz the issue should be gone, we now have this in the POM:
```
<artifactId>actions__setup-gradle</artifactId>
```
please confirm it works fine in your project!

Thanks @Vampire for your help 🙇

**Comment by mareklangiewicz** [comment]
Yes, that fixes it. Thanks @krzema12 and @Vampire !
Also @Vampire your gut feeling was right :) I had mavenLocalFootgun enabled :)
