### ISSUE TITLE
Consider choosing custom domain

### ISSUE THREAD

**Issue by jmfayard** [typesafegithub/github-workflows-kt#465]
One another thing, related to the name debate, you should pause and reflect before 1.0 is whether to keep the current website URL or move to your own domain name.

https://krzema12.github.io/github-actions-kotlin-dsl/ 

vs 

https://gakd.io (not the actual name)

**Comment by jmfayard** [comment]
My experience on this issue:

The docs for refreshVersions are also stored on GitHub pages at https://jmfayard.github.io/refreshVersions/
Now I thought many times whether I should move away from GitHub pages or not.
Because to be frank it's more a quick and dirty solution than a great long term solution.

I looks more professional to have your own DNS like https://kotest.io/

Now you may think that you can just choose your DNS and keep GitHub pages.
But there are some support for it, the documentation and everything else is in fact quite bad, it was never designed for that.

My experience is that https://www.netlify.com/ takes care of everything (deployment, reporting, custom domain name, dns configuration, SSL, ...) in a much easier way.

**Comment by krzema12** [comment]
I'm thinking about a compromise: creating a GitHub org named `github-workflows-kt`, thanks to this we could have docs hosted at https://github-workflows-kt.github.io/docs (in `docs` repository) and it's for free. For now I have mixed feeling when thinking about paying over 200 PLN for a custom domain.

**Comment by krzema12** [comment]
A possibly bearable price:
![Screenshot_2022-11-21-08-21-53-801-edit_com android chrome](https://user-images.githubusercontent.com/3110813/202989091-4904abb2-80e1-4dae-88fd-01e8cc7542d6.jpg)

**Comment by jmfayard** [comment]
That's the normal price. It's only `.io` which is expansive.
The domain name is a nice too have and optional though, don't worry too much about it.

**Comment by krzema12** [comment]
Started moving to https://github.com/typesafegithub/, which will also let us use a domain io.github.typesafegithub.

https://kotlinlang.slack.com/archives/C02UUATR7RC/p1680373704881049

**Comment by krzema12** [comment]
Requesting new group ID in Maven Central: https://issues.sonatype.org/browse/OSSRH-90368

**Comment by krzema12** [comment]
This is almost done, let's wait for publishing the next release to confirm that everything works fine after moving things around.

**Comment by krzema12** [comment]
TODO: adjust the teaser image https://github.com/typesafegithub/github-workflows-kt/commit/1c612284ef71e1e7c44709485f28530d1c92fd7a
