### ISSUE TITLE
Encourage action owners to onboard github-actions-typing

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#567]
* 8398a7/action-slack
 * actions-rs/audit-check
 * actions-rs/cargo
 * actions-rs/clippy-check
 * actions-rs/toolchain
 * actions/cache/restore
 * actions/cache/save
 * actions/cache
 * actions/checkout
 * actions/create-release
 * actions/download-artifact
 * actions/first-interaction
 * actions/github-script
 * actions/labeler
 * actions/setup-dotnet
 * actions/setup-go
 * actions/setup-java
 * actions/setup-node
 * actions/setup-python
 * actions/stale - https://github.com/actions/stale/pull/830
 * actions/typescript-action - https://github.com/actions/typescript-action/issues/591
 * actions/upload-artifact
 * anmol098/waka-readme-stats
 * anothrNick/github-tag-action
 * aws-actions/amazon-ecr-login
 * aws-actions/amazon-ecs-deploy-task-definition
 * aws-actions/amazon-ecs-render-task-definition
 * aws-actions/configure-aws-credentials
 * axel-op/googlejavaformat-action
 * Azure/docker-login
 * Azure/login
 * Azure/webapps-deploy
 * bahmutov/npm-install - https://github.com/bahmutov/npm-install/pull/148
 * Borales/actions-yarn - https://github.com/Borales/actions-yarn/issues/52
 * burrunan/gradle-cache-action - https://github.com/burrunan/gradle-cache-action/pull/59
 * c2corg/browserslist-update-action - :purple_heart: https://github.com/c2corg/browserslist-update-action/commit/c9492fdf2e05303c4a5159bd5d4b108a92a4f419
 * c2corg/transifex-pull-request-action - :purple_heart: https://github.com/c2corg/transifex-pull-request-action/commit/871f9e05b06923c57bc00263f45c718d43634dba
 * cachix/install-nix-action
 * codecov/codecov-action
 * docker/build-push-action - https://github.com/docker/build-push-action/issues/789
 * docker/login-action
 * docker/setup-buildx-action
 * elgohr/Publish-Docker-Github-Action
 * EndBug/add-and-commit
 * entrostat/git-secret-action - https://github.com/entrostat/git-secret-action/pull/3
 * ericcornelissen/git-tag-annotation-action - https://github.com/ericcornelissen/git-tag-annotation-action/pull/262
 * gautamkrishnar/blog-post-workflow - https://github.com/gautamkrishnar/blog-post-workflow/pull/149
 * google-github-actions/auth
 * google-github-actions/setup-gcloud
 * GoogleCloudPlatform/github-actions
 * gradle-update/update-gradle-wrapper-action
 * gradle/gradle-build-action
 * gradle/wrapper-validation-action
 * JamesIves/github-pages-deploy-action
 * JasonEtco/create-an-issue
 * julia-actions/setup-julia
 * krzema12/github-actions-typing - :purple_heart: https://github.com/krzema12/github-actions-typing/commit/39ca5c89e5654f2c294c8fa7e09dcb7fda39ce9a
 * madhead/check-gradle-version - 💜 https://github.com/madhead/check-gradle-version/commit/5cb740d5f6bffebd4fa9e14ea4af0305c6842a59
 * madhead/intellij-http-client-action - 💜 https://github.com/madhead/intellij-http-client-action/commit/2a46bb002624639ac41a146b04cecdc683d5e31a
 * madhead/semver-utils - 💜 https://github.com/madhead/semver-utils/commit/265d815798fcb6423d700cc9d6afbed8f92453dd
 * mi-kas/kover-report - https://github.com/mi-kas/kover-report/issues/34
 * microsoft/setup-msbuild - https://github.com/microsoft/setup-msbuild/issues/109
 * nobrayner/discord-webhook - https://github.com/nobrayner/discord-webhook/issues/6
 * peaceiris/actions-gh-pages - https://github.com/peaceiris/actions-gh-pages/discussions/848
 * peaceiris/actions-hugo - https://github.com/peaceiris/actions-hugo/discussions/626
 * peter-evans/create-issue-from-file - https://github.com/peter-evans/create-issue-from-file/issues/788
 * peter-evans/create-pull-request - https://github.com/peter-evans/create-pull-request/issues/1574
 * ReactiveCircus/android-emulator-runner - https://github.com/ReactiveCircus/android-emulator-runner/issues/268
 * repo-sync/pull-request - https://github.com/repo-sync/pull-request/issues/131
 * ruby/setup-ruby - https://github.com/ruby/setup-ruby/issues/458
 * softprops/action-gh-release - https://github.com/softprops/action-gh-release/issues/282
 * stefanzweifel/git-auto-commit-action - https://github.com/tailwindlabs/tailwindcss/discussions/10463
 * subosito/flutter-action - https://github.com/subosito/flutter-action/issues/203
 * supercharge/mongodb-github-action - https://github.com/supercharge/mongodb-github-action/issues/44
 * Vampire/setup-wsl - https://github.com/Vampire/setup-wsl/pull/30

**Comment by LeoColman** [comment]
https://github.com/entrostat/git-secret-action/pull/3

**Comment by krzema12** [comment]
I decided to stop advertising this tool actively - let's rely on natural adoption.
