### ISSUE TITLE
Host a simple JVM app (YAML to Kotlin converter) to make it easier for people to try things out

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#571]
[Great brainstorming session on kotlinlang#server](https://kotlinlang.slack.com/archives/C02UUATR7RC/p1669500030127449?thread_ts=1669498777.877479&cid=C02UUATR7RC)

## What's the issue?
Free hosting question, or lack thereof thanks to the crypto scammers and stuff.

I am working with [@Piotr Krzemiński](https://kotlinlang.slack.com/team/UQX3ZNU12) on the [#github-workflows-kt](https://kotlinlang.slack.com/archives/C02UUATR7RC) open source project,  
 that wants to free the world to have to write YAML for their GitHub Actions. We have a YAML to Kotlin converter that works fine locally.  
But we are stuck because we would like to host it as a JVM server, and all free hosting plans are gone thanks to all those crypto scammers.  
For an open source project it’s annoying to have to pay every month for one little converter like that.  
Can you think of a work-around? like having a nice sponsor, gaining startup credits somewhere or something like that

We need something like this web tool, but with Kotlin and YAML instead of YAML and JSON
https://www.json2yaml.com/

The current YAML to Kotlin converter needs the user to download the project, and do weird Gradle stuff.
[https://typesafegithub.github.io/github-workflows-kt/user-guide/script-generator/](https://typesafegithub.github.io/github-workflows-kt/user-guide/script-generator/)

## Hosting platforms

**Fly** https://fly.io/ was mentionned by David http4k and praised by Johann as a great hosting platform
Free plan is probably enough given how few things we need
https://fly.io/docs/about/pricing/

**AWS** is the obvious elephant in the room.
**AWS Lambda** has a limit of 1 million free request per month which should be enough for one or two months given our meteorit success. 
But **cold start** is an issue as noted by David. 
If we do we should use http4k and GraalVM https://www.http4k.org/guide/tutorials/going_native_with_graal_on_aws_lambda/

**Oracle** has a free tier but its UX suck so we don't use it, because our time is not free.
https://www.oracle.com/de/cloud/free/

**Google Cloud Platform** : https://cloud.google.com/free
**Martin** has [an example to deploy to appengine](https://github.com/martinbonnin/Confetti-backend/blob/main/build.gradle.kts#L41), advises that their UX sucks. He also says that we _you get "only" 256MB of RAM which the JVM will happilly use to store metaspace_, which is a real concern, that can also be adressed by http4k because _256Mb is plenty for an http4k app_ says **David**.

David and the http4k project use **Heroku** for $7 a month

**DigitalOcean** has an Open Source sponsoring plan which gives you 5$/month if your project has 500 stars on GitHub. Shit we have only 319 stars, quick we need to spam people. No seriously we can probably reach out and show we are a serious project.

## Pros and cons

I would advise against complex solutions that can become a surprising time sink like Oracle (terrible UX) and AWS as **James Richardson** says: _about how to host a "simple" service. AWS gets surprisingly complex very quickly. IAM + STS, 2FA, Cloudwatch, Pulumi, API GW etc etc._

Other than that, the user doesn't really care which hosting platform we use, but the person doing the work may well do, so I would say that **whoever is ready to do the job can choose whatever make sense.**

## Alternatives to a web tool
Piotr proposed an IDE plugin. David remarked that IntelliJ plugin development is not exactly straightforward.

Björn proposed to have a bootstraping a `.main.kts` script.
Or Piotr's equivalent idea [Create a Kotlin CLI to improve overall developer workflow](https://github.com/typesafegithub/github-workflows-kt/issues/464) 

**Adam S** propose a GitHub action that would create a PR.

**Porting to JavaScript** sounds nice but is also probably way much work that it's worth.

Those are clever ideas but I would advise against being too clever here.
The basic story of the internet is that nothing beats a web tool for trying out something quickly.
We should always keep in mind that not all our potential users are kotlin/Java devs. Everyone who hates to code in YAML is welcome.  
Obviously I like that our project use Kotlin, but I would also gladly use the project if it used typescript/python/whatever-sane-language.

## Original ticket from @krzema12

Ideas how to proceed:
* check the cost of hosting the current solution as a Web service
* see how hard it would be to port script-generator to Kotlin/JS
  * it has two major external dependencies: Kotlin Poet and kaml
* a GitHub action you run once, which produces the Kotlin scripts, runs them, removes itself and commits everything

**Comment by jmfayard** [comment]
🙏🏻  ありがとう @daviddenton @time4tea

**Comment by jmfayard** [comment]
Leonardo Colman from the kotest project aka @LeoColman  can host the server.
By the way let me use the opportunity the op say that I love kotest
@NikkyAI would you want/have the bandwidth to put the Yaml 2 Kotlin converter on the web?

**Comment by krzema12** [comment]
A prerequisite: https://github.com/typesafegithub/github-workflows-kt/issues/758

**Comment by krzema12** [comment]
Working on a MVP UI here: https://github.com/typesafegithub/github-workflows-kt/tree/571-script-generator-ui

**Comment by krzema12** [comment]
Current state: the Web app is hosted by @LeoColman here: https://github-workflows-kt.colman.com.br/. The UI is very simple now, to be enhanced.

**Comment by krzema12** [comment]
Closing per https://github.com/typesafegithub/github-workflows-kt/issues/844
