### ISSUE TITLE
Find a second Maintainer

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#727]
When going 1.0, I'd like to have a person that will be able to participate in discussions as an co-owner of the lib, be able to release if I'm unable to, make hot fixes.

**Comment by benkeil** [comment]
I would be interested

**Comment by krzema12** [comment]
Hi @benkeil, that's cool! Are you on Kotlin Slack so that we can talk directly?

**Comment by benkeil** [comment]
I requested access

**Comment by krzema12** [comment]
@Vampire agreed to be an emergency contact if a hotfix needs to be made :muscle: 
@benkeil is ramping up as a regular contributor :rocket:

It's looking good enough to consider this task resolved.
