### ISSUE TITLE
[Core feature request] provide a Gradle plugin

### ISSUE THREAD

**Issue by benkeil** [typesafegithub/github-workflows-kt#739]
**What feature do you need?**

Because it seems to be impossible at the moment, to use a private maven registry with kotlin script, another possibility would be a cradle script.

**Do you have an example usage?**

I have an example implementation that uses the following API:

**settings.gradle.kts**

```kotlin
gitHubActions {
  workflows(
    workflow(name = "test-1", targetFileName = "workflow-1.yaml", on = listOf(Push())) {
      job("job-1", runsOn = RunnerType.UbuntuLatest) {
        run("command")
      }
    }
  )
}
```

`gitHubActions` automatically calls `writeToFile` for each workflow.

I would also suggest to separate the concerns of writing a file and define a workflow.

If I define a workflow in my library I don't know what user do with it, so it's hard to already define the output filename. It would also be nice if I don't need to specify the yaml extension for `targetFileName`. 

A better API would be something like:

**settings.gradle.kt**

```kotlin
gitHubActions {
  "workflow-1" to workflow(name = "test-1", on = listOf(Push())) {
    job("job-1", runsOn = RunnerType.UbuntuLatest) {
      run("command")
    }
  }
  "workflow-2" to myWorkflowDefinitionFromAPrivateRepository()
}
```

where the key of the pair defines the `targetFileName`.

If you have a lot of homogne services it makes also sense to do something like this:

**settings.gradle.kt**

```kotlin
gitHubActions {
  myAwsLambdaWorkflows()
}

gitHubActions {
  myEc2Workflows()
}
```

**Comment by krzema12** [comment]
Hi @benkeil!

Some adjustments to be able to use the library in "stand-alone" mode were made in https://kotlinlang.slack.com/archives/C02UUATR7RC/p1675057138707659?thread_ts=1675057138.707659&cid=C02UUATR7RC. Are they not enough for this use case?

Regarding the general idea of a Gradle plugin, I agree it could be nice. However, I personally cannot afford creating and maintaining it right now, I hardly keep up with maintenance of the core library. I'd be happy to accept contributions, though.

**Comment by krzema12** [comment]
I think realistically it won't happen, there's no much demand for it. This library will remain script-first, exposing some API for folks that prefer more customization. Let me close, and we can reopen if there's a compelling reason.
