### ISSUE TITLE
[Core feature request] runsOn should accept a list

### ISSUE THREAD

**Issue by benkeil** [typesafegithub/github-workflows-kt#750]
**What feature do you need?**

from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on:

> If you specify an array of strings, your workflow will execute on any runner that matches all of the specified runs-on values.

**Do you have an example usage?**

```yaml
jobs:
  build:
    runs-on: [self-hosted, X64]
```

**Is there a workaround for not having this feature? If yes, please describe it.**

no

**Comment by krzema12** [comment]
It should be possible to work around it in a type-unsafe way using [_customArguments](https://typesafegithub.github.io/github-workflows-kt/user-guide/compensating-librarys-missing-features/).
