### ISSUE TITLE
[Action wrapper(s) request] action-for-semantic-release

### ISSUE THREAD

**Issue by benkeil** [typesafegithub/github-workflows-kt#751]
### Are you sure the action(s) you want aren't already supported?

Yes

### What action(s) do you need?

https://github.com/marketplace/actions/action-for-semantic-release

### Do the actions fulfill all [the requirements](https://krzema12.github.io/github-workflows-kt/user-guide/using-actions/#requirements-for-adding-a-new-action)?

This link is broken

**Comment by krzema12** [comment]
@benkeil you don't have to block on the above ticket to add support for this action. Just place the typings in our library, and if the action owner agrees to provide the typings, we'll switch to using them.
