### ISSUE TITLE
[Core feature request] add `if` as an alias for `condition`

### ISSUE THREAD

**Issue by benkeil** [typesafegithub/github-workflows-kt#752]
**What feature do you need?**

I need to skip jobs based on the output of a previous job/step.

**Do you have an example usage?**

https://github.com/orgs/community/discussions/25280

**Is there a workaround for not having this feature? If yes, please describe it.**

Not sure

**Comment by krzema12** [comment]
https://github.com/typesafegithub/github-workflows-kt/blob/49c956c06ffd56cedac3abe7e373e08eaf962933/library/src/test/kotlin/io/github/typesafegithub/workflows/IntegrationTest.kt#L243-L254

Line 247 - is that what you need? Additionally you can use `expr { }` to make it a bit nicer: https://typesafegithub.github.io/github-workflows-kt/user-guide/type-safe-expressions/

**Comment by benkeil** [comment]
I was only searching for `if`, maybe that's confusing for other people too?

**Comment by krzema12** [comment]
What do you propose instead? `if` is a keyword, we'd have to write

```kotlin
`if` = "..."
```

Maybe it's actually nicer. A matter of opinion :)

**Comment by krzema12** [comment]
@Vampire @NikkyAI @jmfayard since you've been using the lib for some time now, what's your take on this? Should we change the current API?

**Comment by Vampire** [comment]
I also prefer avoiding keywords outside of generated code, as the backticks are poisen for readability imho.
I personally am pretty fine with `condition`.
I also did not really have problems finding it, but maybe because I assumed that such a basic functionality cannot be missing. :-D
That's the good thing with IDE support, it shows you what is available. :-)

**Comment by NikkyAI** [comment]
the main problem I see is people looking for the thing they saw in githubs documentation.. and overlooking or forgetting `condition` is what the equivalent is..

can we just have both ?

**Comment by benkeil** [comment]
I agree that ``if`` looks ugly, but as @NikkyAI mentioned, that’s the way I believe people will use it. And I think it should be as easy as possible for new user.

**Comment by krzema12** [comment]
I'm fine with having an alias like this. Then the user can choose whether to use something closer to the YAML, or something without the backticks.

**Comment by Vampire** [comment]
What if both are set? I'd suggest an error in that case.

**Comment by krzema12** [comment]
@benkeil thanks for helping with this!
