### ISSUE TITLE
[Bug] API docs link is broken on documentation site

### ISSUE THREAD

**Issue by krisbitney** [typesafegithub/github-workflows-kt#779]
The `API Docs` menu item on the left side of the docs website https://typesafegithub.github.io/github-workflows-kt/ is broken.

The link https://krzema12.github.io/github-workflows-kt/api-docs/ produces a 404 not found error.

It seems the correct link should be https://typesafegithub.github.io/github-workflows-kt/api-docs/

**Comment by krzema12** [comment]
Thanks, already fixed in https://github.com/typesafegithub/github-workflows-kt/commit/f73e4e14a07be7fa3189652e8f1906a9c4bce9ef, pending release next week.
