### ISSUE TITLE
[Bug] Some tests for script-generator don't work

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#800]
See https://kotlinlang.slack.com/archives/C02UUATR7RC/p1682589060948629?thread_ts=1682589060.948629&cid=C02UUATR7RC

**Comment by Jan-Ove** [comment]
I can look into this.

**Comment by krzema12** [comment]
Closing per https://github.com/typesafegithub/github-workflows-kt/issues/844
