### ISSUE TITLE
Proposed update for README intro

### ISSUE THREAD

**Issue by aSemy** [typesafegithub/github-workflows-kt#855]
I think the README intro paragraph should be re-written https://github.com/typesafegithub/github-workflows-kt#readme

It starts off by talking about YAML, which I don’t think is a strong start. I’d expect it to start with a strong statement about what workflows-kt is and does before talking about what problems it solves. For example:

> [workflows-kt](https://github.com/typesafegithub/github-workflows-kt) is a tool for creating GitHub Workflows in a _typesafe_ script, helping you to build robust workflows for your GitHub projects without mistakes. You won’t go back to YAML!

(just an example to show my point, I think it should be expanded a little more)

* It's a good idea to have a link back to the repo to help [when the repo gets rehosted](https://sourcegraph.com/github.com/typesafegithub/github-workflows-kt)
* The catchphrase `"You won't get back to YAML!"` is good, but a little awkward in English (but maybe that's the point, and it's hard to judge if it's intended to be a little off :)) - `"You won't go back to YAML!"` flows better.

**Comment by krzema12** [comment]
@aSemy thanks! Please review: https://github.com/typesafegithub/github-workflows-kt/pull/859
