### ISSUE TITLE
Improve caching Gradle state on CI

### ISSUE THREAD

**Issue by krzema12** [typesafegithub/github-workflows-kt#890]
https://slack-chats.kotlinlang.org/t/12918775/i-m-wondering-what-i-m-doing-wrong-when-it-comes-to-caching-

**Comment by Vampire** [comment]
Please don't wonder, I replaced the Slack-link by a linen-link, as it then is not bound to the 90 day limit and also can be looked at without starting / using Slack.

**Comment by krzema12** [comment]
Let's try enabling configuration cache as well.

**Comment by krzema12** [comment]
```
Configuration cache problems found in this build.

4 problems were found storing the configuration cache, 2 of which seem unique.
- Task `:library:validateDuplicatedVersion` of type `org.gradle.api.DefaultTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:library:validateDuplicatedVersion` of type `org.gradle.api.DefaultTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

**Comment by krzema12** [comment]
Removing references to `project` (at least the explicit ones) is easy. However, I have a problem understanding the other issue regarding serializing Gradle script object.

**Comment by Vampire** [comment]
You access `$version` in the task action.
This has an implicit reference to the script instance as that has the property you are reading.
IF you add a `val version = version` within the task configuration closure but outside the `doLast { ... }` should be enough to fix the problem as then only the value is captured, not a reference to the script instance.

**Comment by krzema12** [comment]
I started adopting the project to work with Gradle configuration cache. Some still issues appear - let me wait the full release cycle (2 weeks) to give a chance of all relevant workflows to run, and fix the build logic if needed.

**Comment by krzema12** [comment]
Publishing is broken: https://github.com/typesafegithub/github-workflows-kt/actions/runs/6987650312/job/19014417902

```
15 problems were found storing the configuration cache, 6 of which seem unique.
- Task `:closeSonatypeStagingRepository` of type `io.github.gradlenexus.publishplugin.CloseNexusStagingRepository`: cannot serialize object of type 'org.gradle.api.DefaultTask', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:closeSonatypeStagingRepository` of type `io.github.gradlenexus.publishplugin.CloseNexusStagingRepository`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:initializeSonatypeStagingRepository` of type `io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository`: cannot serialize object of type 'org.gradle.api.DefaultTask', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:initializeSonatypeStagingRepository` of type `io.github.gradlenexus.publishplugin.InitializeNexusStagingRepository`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:releaseSonatypeStagingRepository` of type `io.github.gradlenexus.publishplugin.ReleaseNexusStagingRepository`: cannot serialize object of type 'org.gradle.api.DefaultTask', a subtype of 'org.gradle.api.Task', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:task_access
- Task `:releaseSonatypeStagingRepository` of type `io.github.gradlenexus.publishplugin.ReleaseNexusStagingRepository`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.4/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

We either fix till the next release, or ignore it: https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage:ignore_problems

**Comment by krzema12** [comment]
I also noticed that on CI, the cache looks like it isn't preserved. I see this all the time:

```
Calculating task graph as no configuration cache is available for tasks: build
```

**Comment by krzema12** [comment]
Workdlows that usually run periodically work fine:
* https://github.com/typesafegithub/github-workflows-kt/actions/runs/6988312072
* https://github.com/typesafegithub/github-workflows-kt/actions/runs/6988312448

**Comment by Vampire** [comment]
> We either fix till the next release

You cannot, until you wait for Gradle 9 and the release of the nexus publish plugin following that one: gradle-nexus/publish-plugin#221

> or ignore it:

Don't do that. This setting is not something you should use in production. It is just to find some more issues while the build is not yet fully CC compatible. Also, setting it will in many cases not mean that the build suddenly will work, it often just fails later and harder. Just don't try to use CC on publishing currently, on GHA it is not reused anyway.

> I also noticed that on CI, the cache looks like it isn't preserved. I see this all the time:

Correct, the Gradle build action does not preserve the configuration cache.

**Comment by krzema12** [comment]
Requested adding support for configuration cache state storing: https://github.com/gradle/gradle-build-action/issues/966

**Comment by Vampire** [comment]
The code is already there, just the call is commented out. I guess it does not yet work properly as the cache is not yet relocatable

**Comment by krzema12** [comment]
I pushed it as far as possible right now. Let's resolve it for now.
